
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* image
* filename: /home/void/Documents/Wiring/Information for Information for ePaper/pixelated icons/battery icon *.xml
* name: battery_icon
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;

#include <stdint.h>

static const uint8_t image_data_battery_icon_full[45] = {/*
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙███∙███∙███∙██∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙*/
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0, 
    0xc0, 0x00, 0x3c, 
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4,
    0xdd, 0xdd, 0xb4, 
    0xdd, 0xdd, 0xb4,
    0xc0, 0x00, 0x3c, 
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0
};
const tImage battery_icon_full = { image_data_battery_icon_full, 23, 15,
    8 };

static const uint8_t image_data_battery_icon_high[45] = {/*
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙*/
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0, 
    0xc0, 0x00, 0x3c, 
    0xdd, 0xdc, 0x34, 
    0xdd, 0xdc, 0x34, 
    0xdd, 0xdc, 0x34,
    0xdd, 0xdc, 0x34,
    0xdd, 0xdc, 0x34, 
    0xdd, 0xdc, 0x34, 
    0xdd, 0xdc, 0x34,
    0xdd, 0xdc, 0x34, 
    0xdd, 0xdc, 0x34,
    0xc0, 0x00, 0x3c, 
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0
};
const tImage battery_icon_high = { image_data_battery_icon_high, 23, 15,
    8 };

static const uint8_t image_data_battery_icon_half[45] = {/*
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙███∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙*/
    0xff, 0xff, 0xe0,
    0xff, 0xff, 0xe0,
    0xc0, 0x00, 0x3c, 
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34, 
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34,
    0xdd, 0xc0, 0x34,
    0xc0, 0x00, 0x3c,
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0
};
const tImage battery_icon_half = { image_data_battery_icon_half, 23, 15,
    8 };

static const uint8_t image_data_battery_icon_low[45] = {/*
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙*/
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0,
    0xc0, 0x00, 0x3c, 
    0xdc, 0x00, 0x34, 
    0xdc, 0x00, 0x34, 
    0xdc, 0x00, 0x34,
    0xdc, 0x00, 0x34, 
    0xdc, 0x00, 0x34, 
    0xdc, 0x00, 0x34,
    0xdc, 0x00, 0x34,
    0xdc, 0x00, 0x34, 
    0xdc, 0x00, 0x34,
    0xc0, 0x00, 0x3c, 
    0xff, 0xff, 0xe0,
    0xff, 0xff, 0xe0
};
const tImage battery_icon_low = { image_data_battery_icon_low, 23, 15,
    8 };

static const uint8_t image_data_battery_icon_empty[45] = {/*
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙███∙██████████∙██∙█∙
    ██∙███∙██████████∙██∙█∙
    ██∙███∙██████████∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙*/
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0, 
    0xc0, 0x00, 0x3c, 
    0xc0, 0x00, 0x34,
    0xc0, 0x00, 0x34,
    0xc0, 0x00, 0x34,
    0xdd, 0xff, 0xb4,
    0xdd, 0xff, 0xb4, 
    0xdd, 0xff, 0xb4,
    0xc0, 0x00, 0x34,
    0xc0, 0x00, 0x34, 
    0xc0, 0x00, 0x34,
    0xc0, 0x00, 0x3c, 
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0
};
const tImage battery_icon_empty = { image_data_battery_icon_empty, 23, 15,
    8 };

static const uint8_t image_data_battery_icon_recharge[45] = {/*
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙∙∙∙∙∙∙███∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙████∙∙∙∙∙██∙█∙
    ██∙██∙∙∙∙█████∙∙∙∙██∙█∙
    ██∙███∙∙∙██∙███∙∙∙██∙█∙
    ██∙████∙∙██∙∙███∙∙██∙█∙
    ██∙∙████∙██∙∙∙███∙██∙█∙
    ██∙∙∙██████∙∙∙∙██∙██∙█∙
    ██∙∙∙∙█████∙∙∙∙∙█∙██∙█∙
    ██∙∙∙∙∙████∙∙∙∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙*/
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0, 
    0xc0, 0x00, 0x3c, 
    0xc0, 0x70, 0x34,
    0xc0, 0x78, 0x34,
    0xd8, 0x7c, 0x34,
    0xdc, 0x6e, 0x34,
    0xde, 0x67, 0x34, 
    0xcf, 0x63, 0xb4,
    0xc7, 0xe1, 0xb4,
    0xc3, 0xe0, 0xb4, 
    0xc1, 0xe0, 0x34,
    0xc0, 0x00, 0x3c, 
    0xff, 0xff, 0xe0, 
    0xff, 0xff, 0xe0
};
const tImage battery_icon_recharge = { image_data_battery_icon_recharge, 23, 15,
    8 };
