
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* image
* filename: /home/void/Documents/Wiring/Information for Information for ePaper/pixelated icons/battery icon discharge 1.xml
* name: battery_icon
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_battery_icon[45] = {
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙███∙███∙███∙∙∙∙██∙█∙
    ██∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙████∙
    ███████████████████∙∙∙∙
    ███████████████████∙∙∙∙
    0xff, 0xff, 0xe0, 0xff, 0xff, 0xe0, 0xc0, 0x00, 
    0x3c, 0xdd, 0xdc, 0x34, 0xdd, 0xdc, 0x34, 0xdd, 
    0xdc, 0x34, 0xdd, 0xdc, 0x34, 0xdd, 0xdc, 0x34, 
    0xdd, 0xdc, 0x34, 0xdd, 0xdc, 0x34, 0xdd, 0xdc, 
    0x34, 0xdd, 0xdc, 0x34, 0xc0, 0x00, 0x3c, 0xff, 
    0xff, 0xe0, 0xff, 0xff, 0xe0
};
const tImage battery_icon = { image_data_battery_icon, 23, 15,
    8 };
