
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* image
* filename: /home/void/Documents/Wiring/Information for Information for ePaper/pixelated icons/Internet Connection.xml
* name: Internet Connection
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_InternetConnection[90] = {
    ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙█████∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙███∙∙∙∙∙██∙∙██∙∙∙
    ∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙
    ∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙
    ∙█∙∙∙∙∙∙∙∙∙∙∙∙∙∙███∙∙∙∙
    ∙∙∙∙∙∙∙∙█████∙∙∙██∙∙∙∙∙
    ∙∙∙∙∙∙███████∙∙██∙∙∙∙∙∙
    ∙∙∙∙████∙∙∙∙∙∙███∙∙∙∙∙∙
    ∙∙████∙∙∙∙∙∙∙∙██∙∙∙██∙∙
    ∙███∙∙∙∙██∙∙∙███∙∙∙███∙
    ∙█∙∙∙∙████∙∙∙██∙∙∙∙∙∙█∙
    ∙∙∙∙████∙∙∙∙██∙∙∙██∙∙∙∙
    ∙∙∙███∙∙∙∙∙███∙∙∙███∙∙∙
    ∙∙██∙∙∙∙∙∙∙██∙∙∙∙∙∙██∙∙
    ∙∙█∙∙∙∙∙∙∙███∙█∙∙∙∙∙█∙∙
    ∙∙∙∙∙∙█∙∙∙██∙∙███∙∙∙∙∙∙
    ∙∙∙∙∙██∙∙██∙∙∙∙███∙∙∙∙∙
    ∙∙∙∙██∙∙███∙∙∙∙∙∙██∙∙∙∙
    ∙∙∙∙█∙∙∙██∙∙██∙∙∙∙█∙∙∙∙
    ∙∙∙∙∙∙∙███∙∙████∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙██∙∙∙∙∙███∙∙∙∙∙∙
    ∙∙∙∙∙∙██∙∙∙∙∙∙∙∙█∙∙∙∙∙∙
    ∙∙∙∙∙███∙∙███∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙██∙∙█████∙∙∙∙∙∙∙∙∙
    ∙∙∙∙██∙∙∙█████∙∙∙∙∙∙∙∙∙
    ∙∙∙∙██∙∙∙█████∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x7c, 0x00, 0x03, 0x83, 
    0x30, 0x0c, 0x00, 0x30, 0x30, 0x00, 0x60, 0x40, 
    0x00, 0xe0, 0x00, 0xf8, 0xc0, 0x03, 0xf9, 0x80, 
    0x0f, 0x03, 0x80, 0x3c, 0x03, 0x18, 0x70, 0xc7, 
    0x1c, 0x43, 0xc6, 0x04, 0x0f, 0x0c, 0x60, 0x1c, 
    0x1c, 0x70, 0x30, 0x18, 0x18, 0x20, 0x3a, 0x08, 
    0x02, 0x33, 0x80, 0x06, 0x61, 0xc0, 0x0c, 0xe0, 
    0x60, 0x08, 0xcc, 0x20, 0x01, 0xcf, 0x00, 0x01, 
    0x83, 0x80, 0x03, 0x00, 0x80, 0x07, 0x38, 0x00, 
    0x06, 0x7c, 0x00, 0x0c, 0x7c, 0x00, 0x0c, 0x7c, 
    0x00, 0x00, 0x38, 0x00, 0x00, 0x00, 0x00, 0x00, 
    0x00, 0x00
};
const tImage InternetConnection = { image_data_InternetConnection, 23, 30,
    8 };
