
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* image
* filename: /home/void/Documents/Wiring/Information for Information for ePaper/pixelated icons/pressure trend.xml
* name: trend
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_trend[25] = {
    ∙∙∙█∙∙∙
    ∙∙███∙∙
    ∙█████∙
    ∙█████∙
    ███████
    ███████
    ███████
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    ∙∙███∙∙
    0x10, 0x38, 0x7c, 0x7c, 0xfe, 0xfe, 0xfe, 0x38, 
    0x38, 0x38, 0x38, 0x38, 0x38, 0x38, 0x38, 0x38, 
    0x38, 0x38, 0x38, 0x38, 0x38, 0x38, 0x38, 0x38, 
    0x38
};
const tImage trend = { image_data_trend, 7, 25,
    8 };
