
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* image
* filename: /home/void/Documents/Wiring/Information for Information for ePaper/pixelated icons/fire icon.xml
* name: pixelated fire icon
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_pixelatedfireicon[124] = {
    ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙██∙∙██∙∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙██∙∙████∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙██∙∙∙████∙∙∙∙∙∙∙
    ∙∙∙∙∙█∙∙∙██∙∙∙∙████∙∙∙∙∙∙
    ∙∙∙∙∙█∙∙██∙∙∙∙∙█████∙∙∙∙∙
    ∙∙∙∙∙██∙██∙∙∙∙∙█████∙∙∙∙∙
    ∙∙∙∙∙█████∙∙∙∙∙∙██∙██∙∙∙∙
    ∙∙∙∙∙████∙∙∙∙∙∙∙██∙██∙∙∙∙
    ∙∙∙∙████∙∙∙∙∙∙∙∙█∙∙∙██∙∙∙
    ∙∙∙∙████∙∙∙∙∙∙∙∙∙∙∙∙██∙∙∙
    ∙∙∙████∙∙∙∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    ∙∙∙██∙∙∙∙∙∙∙██∙∙∙∙∙∙∙█∙∙∙
    ∙∙███∙∙∙∙∙∙∙███∙∙∙∙∙∙██∙∙
    ∙∙██∙∙∙∙∙∙█∙████∙∙∙∙∙██∙∙
    ∙∙██∙∙∙∙∙████∙∙██∙∙∙∙██∙∙
    ∙∙██∙∙∙∙∙████∙∙██∙∙∙∙██∙∙
    ∙∙██∙∙∙∙█████∙∙███∙∙██∙∙∙
    ∙∙██∙∙∙∙█∙██∙∙∙∙██∙∙██∙∙∙
    ∙∙∙██∙∙██∙██∙∙∙∙██∙███∙∙∙
    ∙∙∙███∙██∙█∙∙∙∙∙██∙██∙∙∙∙
    ∙∙∙∙█████∙∙∙∙∙∙∙████∙∙∙∙∙
    ∙∙∙∙∙████∙∙∙∙∙∙∙███∙∙∙∙∙∙
    ∙∙∙∙∙∙███∙∙∙∙∙∙███∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙███∙∙∙∙∙██∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙██∙∙∙∙∙██∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙██∙∙∙∙∙█∙∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x30, 0x00, 0x00, 
    0x00, 0x38, 0x00, 0x00, 0x00, 0x3c, 0x00, 0x00, 
    0x00, 0x66, 0x00, 0x00, 0x00, 0x67, 0x80, 0x00, 
    0x00, 0x63, 0xc0, 0x00, 0x04, 0x61, 0xe0, 0x00, 
    0x04, 0xc1, 0xf0, 0x00, 0x06, 0xc1, 0xf0, 0x00, 
    0x07, 0xc0, 0xd8, 0x00, 0x07, 0x80, 0xd8, 0x00, 
    0x0f, 0x00, 0x8c, 0x00, 0x0f, 0x00, 0x0c, 0x00, 
    0x1e, 0x04, 0x04, 0x00, 0x18, 0x0c, 0x04, 0x00, 
    0x38, 0x0e, 0x06, 0x00, 0x30, 0x2f, 0x06, 0x00, 
    0x30, 0x79, 0x86, 0x00, 0x30, 0x79, 0x86, 0x00, 
    0x30, 0xf9, 0xcc, 0x00, 0x30, 0xb0, 0xcc, 0x00, 
    0x19, 0xb0, 0xdc, 0x00, 0x1d, 0xa0, 0xd8, 0x00, 
    0x0f, 0x80, 0xf0, 0x00, 0x07, 0x80, 0xe0, 0x00, 
    0x03, 0x81, 0xc0, 0x00, 0x01, 0xc1, 0x80, 0x00, 
    0x00, 0xc1, 0x80, 0x00, 0x00, 0xc1, 0x00, 0x00, 
    0x00, 0x00, 0x00, 0x00
};
const tImage pixelatedfireicon = { image_data_pixelatedfireicon, 25, 31,
    8 };
