
/*******************************************************************************
* generated by lcd-image-converter rev.4d43872 from 2022-06-23 22:11:57 +0500
* image
* filename: /home/void/Documents/Wiring/Information for ePaper/pixelated icons (second attempt)/trend_even.xml
* name: trend
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: yes
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_trend[29] = {
    ∙∙∙██∙∙∙
    ∙∙∙██∙∙∙
    ∙∙∙██∙∙∙
    ∙∙∙██∙∙∙
    ∙∙████∙∙
    ████████
    ████████
    ████████
    ∙██████∙
    ∙██████∙
    ∙∙████∙∙
    ∙∙████∙∙
    ∙∙∙██∙∙∙
    ∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙
    ∙∙∙∙∙∙∙∙
    ∙∙∙██∙∙∙
    ∙∙████∙∙
    ∙∙████∙∙
    ∙██████∙
    ∙██████∙
    ████████
    ████████
    ████████
    ∙∙████∙∙
    ∙∙∙██∙∙∙
    ∙∙∙██∙∙∙
    ∙∙∙██∙∙∙
    ∙∙∙██∙∙∙
    0x18, 0x18, 0x18, 0x18, 0x3c, 0xff, 0xff, 0xff, 
    0x7e, 0x7e, 0x3c, 0x3c, 0x18, 0x00, 0x00, 0x00, 
    0x18, 0x3c, 0x3c, 0x7e, 0x7e, 0xff, 0xff, 0xff, 
    0x3c, 0x18, 0x18, 0x18, 0x18
};
const tImage trend = { image_data_trend, 8, 29,
    8 };
